# Generated by Django 2.2.4 on 2019-09-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCheckUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnatPatMorChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anat_pat_mor_changes', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Behaviour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviour', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BloodChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_changes', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CDRDetectionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_method', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CDRSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ChangesDuringResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_method_text', models.TextField()),
                ('detection_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.CDRDetectionMethod')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.CDRSystem')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_text', models.TextField()),
                ('behaviour_text', models.TextField()),
                ('additional_check_up', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.AdditionalCheckUp')),
                ('behaviour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Behaviour')),
                ('changes_during_research', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.ChangesDuringResearch')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_process', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Feces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feces', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_names_text', models.TextField()),
                ('alternative_text', models.TextField()),
                ('doses', models.CharField(max_length=256)),
                ('medicine_application', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineContradictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contradictions', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_group', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineMarketNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_names', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineOverdose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overdose', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineRecommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineSideEffects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_effects', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UrineChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urine_changes', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('notices', models.TextField()),
                ('off_treatment_procedures', models.TextField()),
                ('medicine_anesthetic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=256)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Race')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='alternative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineAlternative'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='contradictions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineContradictions'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='market_names',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineMarketNames'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineGroup'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='overdose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineOverdose'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='recommendations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineRecommendations'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineSideEffects'),
        ),
        migrations.CreateModel(
            name='MedicalProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immediate_action', models.CharField(max_length=256)),
                ('essential_procedures', models.CharField(max_length=256)),
                ('other_procedures_priority', models.CharField(max_length=256)),
                ('owner_recommendations', models.CharField(max_length=256)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Medicine')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=256)),
                ('name_lat', models.CharField(max_length=256)),
                ('name_en', models.CharField(max_length=256)),
                ('name_other', models.CharField(max_length=256)),
                ('predisposition', models.CharField(max_length=256)),
                ('remarks_comments', models.TextField()),
                ('survivability', models.CharField(max_length=256)),
                ('disease_type', models.CharField(max_length=256)),
                ('diagnostics', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Diagnostics')),
                ('medical_procedure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicalProcedure')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.DiseaseProcess')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Species')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Interview'),
        ),
        migrations.AddField(
            model_name='additionalcheckup',
            name='anat_pat_mor_changes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.AnatPatMorChanges'),
        ),
        migrations.AddField(
            model_name='additionalcheckup',
            name='blood_changes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.BloodChanges'),
        ),
        migrations.AddField(
            model_name='additionalcheckup',
            name='feces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Feces'),
        ),
        migrations.AddField(
            model_name='additionalcheckup',
            name='urine_changes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.UrineChanges'),
        ),
    ]
