# Generated by Django 2.2.4 on 2019-09-05 14:54

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('horsekiller', '0002_auto_20190904_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalcheckup',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='additionalcheckup',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='anatpatmorchanges',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='anatpatmorchanges',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='behaviour',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='behaviour',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='bloodchanges',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='bloodchanges',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='cdrdetectionmethod',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='cdrdetectionmethod',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='cdrsystem',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='cdrsystem',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='changesduringresearch',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='changesduringresearch',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='diagnostics',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='diagnostics',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='diagnosticsphotos',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='diagnosticsphotos',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='diseaseprocess',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='diseaseprocess',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='feces',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='feces',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='medicalprocedure',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='medicalprocedure',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='medicinealternative',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='medicinealternative',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='medicinecontradictions',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='medicinecontradictions',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='medicinegroup',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='medicinegroup',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='medicinemarketnames',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='medicinemarketnames',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='medicineoverdose',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='medicineoverdose',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='medicinerecommendations',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='medicinerecommendations',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='medicinesideeffects',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='medicinesideeffects',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='race',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='race',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='species',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='species',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='urinechanges',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='urinechanges',
            name='likes',
        ),
        migrations.AlterField(
            model_name='additionalcheckup',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='anatpatmorchanges',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='behaviour',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='bloodchanges',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='cdrdetectionmethod',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='cdrsystem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='changesduringresearch',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='additional_check_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.AdditionalCheckUp'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='behaviour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Behaviour'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='changes_during_research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.ChangesDuringResearch'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='incident_photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.DiagnosticsPhotos'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Interview'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='diagnosticsphotos',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='diagnostics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Diagnostics'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='medical_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicalProcedure'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.DiseaseProcess'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Species'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='diseaseprocess',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='feces',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='medicalprocedure',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Medicine'),
        ),
        migrations.AlterField(
            model_name='medicalprocedure',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='medicalprocedure',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Treatment'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='alternative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineAlternative'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='alternative_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='contradictions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineContradictions'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='doses',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='market_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineMarketNames'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='market_names_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_application',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineGroup'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='overdose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineOverdose'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='recommendations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineRecommendations'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='side_effects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.MedicineSideEffects'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='medicinealternative',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='medicinecontradictions',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='medicinegroup',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='medicinemarketnames',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='medicineoverdose',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='medicinerecommendations',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='medicinesideeffects',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='race',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='species',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Race'),
        ),
        migrations.AlterField(
            model_name='species',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='medicine_anesthetic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horsekiller.Medicine'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='urinechanges',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
