# Generated by Django 2.2.4 on 2019-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsekiller', '0003_auto_20190905_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
