# Generated by Django 2.2.4 on 2019-09-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsekiller', '0004_medicine_medicine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='alternative',
        ),
        migrations.AddField(
            model_name='medicine',
            name='alternative',
            field=models.ManyToManyField(blank=True, null=True, to='horsekiller.MedicineAlternative'),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='contradictions',
        ),
        migrations.AddField(
            model_name='medicine',
            name='contradictions',
            field=models.ManyToManyField(blank=True, null=True, to='horsekiller.MedicineContradictions'),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='market_names',
        ),
        migrations.AddField(
            model_name='medicine',
            name='market_names',
            field=models.ManyToManyField(blank=True, null=True, to='horsekiller.MedicineMarketNames'),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_group',
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_group',
            field=models.ManyToManyField(blank=True, null=True, to='horsekiller.MedicineGroup'),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='overdose',
        ),
        migrations.AddField(
            model_name='medicine',
            name='overdose',
            field=models.ManyToManyField(blank=True, null=True, to='horsekiller.MedicineOverdose'),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='medicine',
            name='recommendations',
            field=models.ManyToManyField(blank=True, null=True, to='horsekiller.MedicineRecommendations'),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='side_effects',
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.ManyToManyField(blank=True, null=True, to='horsekiller.MedicineSideEffects'),
        ),
    ]
